### ISSUE TITLE
Flight update SSE doesnt set status correctly

### ISSUE THREAD

**Issue by J-C-V** [MetaEMK/FGK_PASMAS_backend#42]
### Version
main

### Endpoint
/realtime/flights

### Method
GET

### Description
Flight update SSE doesnt set status correctly. Status remains RESERVED even after setting it to BOOKED

Status in response is correct:
![image](https://github.com/MetaEMK/FGK_PASMAS_backend/assets/12070160/906c0b55-28da-405a-81da-d9eb75b3b40e)

Status in SSE is not correct:
![image](https://github.com/MetaEMK/FGK_PASMAS_backend/assets/12070160/694c99bf-408b-44f1-af19-74fe1fb83a70)

### Steps to reproduce
Listening to flight update SSEs.

### Expected behaviour:
SSE contains the correct status.

**Comment by MetaEMK** [comment]
This is already fixed in v0.3 - WIP. If you need this functionality use v0.3 branch until it is fully released.
I have tested it and on v0.3 with commit ed0a944 it worked fine.

If the problem still exists, you can reopen the issue with the following data.

- Version name
- Flight data to be deleted
- Exact response of the backend in the call and in the realtime event
- If possible also the server logs
